### ISSUE TITLE
[Question] - The PARA page query isn't showing my project page..

### ISSUE THREAD

**Issue by dazinator** [georgeguimaraes/logseq-plugin-add-PARA-properties#6]
Thanks for this plugin, I was just trying it out..
I created a new project page

<img width="589" alt="image" src="https://github.com/georgeguimaraes/logseq-plugin-add-PARA-properties/assets/3176632/436801c1-4b9b-4e80-a3fa-bd266372be60">

Over on my root PARA page it doesn't show up...

<img width="836" alt="image" src="https://github.com/georgeguimaraes/logseq-plugin-add-PARA-properties/assets/3176632/81de4f03-d5dc-42e6-a1aa-0ed33525453f">

This is the query

```
<img width="694" alt="image" src="https://github.com/georgeguimaraes/logseq-plugin-add-PARA-properties/assets/3176632/4610735b-e8cd-47d4-8f79-d810d8a4b694">

```

Is that the query that I should be seeing?

**Comment by dazinator** [comment]
At the moment I just replaced it with a very simple query which works

```
{{query (property page-type project)}}
```

<img width="728" alt="image" src="https://github.com/georgeguimaraes/logseq-plugin-add-PARA-properties/assets/3176632/810d3126-a67a-4505-8e4e-3da9e739dbd9">

But I think your query was doing a lot more, so i'd love to see it working!

**Comment by dazinator** [comment]
A bit more refining and this is how I filter out archived things

```
{{query (and (property page-type project) (not(property archived true))))}}
```

**Comment by georgeguimaraes** [comment]
Hi, can you change it to `page-type:: [[Project]]` or `page-type:: [[project]]`? 
Does that work?

**Comment by georgeguimaraes** [comment]
The key for this query in the original one is this part:

```
                    [(get ?prop3 :page-type) ?v]
                    (or [(= ?v "Project")] [(contains? ?v "Project")])
```

You can simplify it to

```
[(get ?prop3 :page-type) "project"]
```

Can you try it too?

I'm sorry, Logseq queries are difficult to debug

**Comment by dazinator** [comment]
Thank you, yes it was a casing thing (upper versus lower case values)

**Comment by dazinator** [comment]
Fyi, after I got it working, I ended up:
- revising the query down a bit based on some other examples I found. I am not sure of the differences but this looked smaller 
- adding a filter to filter out anything with `archived: true` 
dropping it here in case it helps someone else.

```
#+BEGIN_QUERY
{
:title [:b "Pages with type:: 'Area'"]
:query [:find (pull ?block [*])
:where
[?block :block/name ?pagename]
(page-property ?block :page-type "Area")
(not (page-property ?block :archived true)) 
]
:view (fn [result]
        [:div.flex.flex-col
        (for [page result]
          [:a {:href (str "#/page/" (get page :block/original-name))} (get page :block/original-name) ]
          )
       [:hr]
        ]
       )
}
#+END_QUERY

```

**Comment by georgeguimaraes** [comment]
Great example, tks for sharing.

The original query is way bigger because it also treats pages that were linked to as projects, if the link is made using the "project::" property.

This way you don't necessarily need to tag all project pages with "page-type::".

Although this means the query is too complicated.
